version: '3'

services:
  supermarketapi: #nombre de la app establecido en application.properties
    build: supermarket-api #nombre de la carpeta donde está el DockerFile
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://serverapi:3306/supermarketapi?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      serverapi:
          condition: service_healthy
  serverapi: #configuraciones de base de datos dockerizada
    image: mysql:8.0.33 #misma versión que esté en el pom
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: supermarketapi
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10